name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Checkout Tests
        run: |
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/pom.xml -O pom.xml;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/src/test/java/com/github/klefstad_teaching/cs122b/billing/BillingServiceTest.java -O src/test/java/com/github/klefstad_teaching/cs122b/billing/BillingServiceTest.java;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/src/test/resources/application.yml -O src/test/resources/application.yml;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/src/test/resources/billing-test-data.sql -O src/test/resources/billing-test-data.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/src/test/resources/empty-billing-test-data.sql -O src/test/resources/empty-billing-test-data.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/src/test/resources/expected-models.json -O src/test/resources/expected-models.json;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/src/test/resources/idm-test-data.sql -O src/test/resources/idm-test-data.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE3-Billing-Service-Starter/main/src/test/resources/users.json -O src/test/resources/users.json;
      - name: Checkout Other DB Data
        run: |
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE1-IDM-Service-Starter/main/db/idm.sql -O db/idm.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE2-Movies-Service-Starter/main/db/0_genre.sql -O db/0_genre.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE2-Movies-Service-Starter/main/db/1_person.sql -O db/1_person.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE2-Movies-Service-Starter/main/db/2_movie.sql -O db/2_movie.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE2-Movies-Service-Starter/main/db/3_movie_genre.sql -O db/3_movie_genre.sql;
          wget https://raw.githubusercontent.com/klefstad-teaching/CS122B-BE2-Movies-Service-Starter/main/db/4_movie_person.sql -O db/4_movie_person.sql;
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install MySQL
        run: brew install mysql;
      - name: Get Stripe API Key
        run: |
          sed -i '' 's|${STRIPE_API_KEY}|"'$STRIPE_API_KEY'"|' src/test/resources/application.yml;
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      - name: Setup DB
        run: |
          mysql.server start;
          mysql -uroot < db.sql;
          mysql -uroot < db/idm.sql;
          mysql -uroot < db/0_genre.sql;
          mysql -uroot < db/1_person.sql;
          mysql -uroot < db/2_movie.sql;
          mysql -uroot < db/3_movie_genre.sql;
          mysql -uroot < db/4_movie_person.sql;
          mysql -uroot < db/billing_movie_price.sql;
      - name: Autograder
        uses: education/autograding@v1
      - name: Delete Application.yml
        if: always()
        run: |
          rm -P src/test/resources/application.yml;